### ISSUE TITLE
Publish only built files to npm

### ISSUE THREAD

**Issue by QuentinFchx** [RequestNetwork/requestNetwork.js#12]
Currently the whole content of the repo is published to npm (`/src`, `/test`). Are there any reasons?

We should use the `files`([doc](https://docs.npmjs.com/files/package.json#files)) and `main` ([doc](https://docs.npmjs.com/files/package.json#main)) properties of the `package.json` along with a `prepublish` script that will just run `npm run build`.

**Comment by QuentinFchx** [comment]
Looks like it was fixed in https://github.com/RequestNetwork/requestNetwork.js/commit/7014ccea9c9d468a4819097ba8cc26cef160785b! Awesome 😄

**Comment by vrolland** [comment]
From the version **0.1.6** of npm package @requestnetwork/request-network.js:
 - only dist/src is present
 - tslib is used
 - and you don't need to specify the path of requestnetwork.js in the import

Thank you again for your suggestions Quentin
