### ISSUE TITLE
Typescript strict mode

### ISSUE THREAD

**Issue by arjunyel** [RequestNetwork/requestNetwork.js#2]
I think this library would benefit alot from turning on Typescript's strict mode. Thank you! https://blog.mariusschulz.com/2017/06/09/typescript-2-3-the-strict-compiler-option

**Comment by vrolland** [comment]
Hello Arjunyel, Thanks for the feedback. 

We will take a look at the article you put here. And we will probably clean the code to have it in "Typescript's strict mode".

Best,

**Comment by vrolland** [comment]
Strict mode enabled in the commit a52a155c0c9a9c32ea27d9cc81e47c37167b424f
