### ISSUE TITLE
Missing dependency when running tests

### ISSUE THREAD

**Issue by myamout** [RequestNetwork/requestNetwork.js#20]
When running `npm run testunit` console complains that it cannot find "ethereumjs-abi". Running `npm i ethereumjs-abi` fixes the issue

**Comment by vrolland** [comment]
fix in last commit 63324478a3b6e72609cfa974267fc6afeb13f566

Thanks myamout

**Comment by myamout** [comment]
Awesome thanks! I'll close the issue then
