### ISSUE TITLE
Missing dependencies when installing from NPM

### ISSUE THREAD

**Issue by myamout** [RequestNetwork/requestNetwork.js#21]
When importing RequestNetwork class after installing from NPM the console complains about a lot of missing dependencies. Not sure if this is correct or not, but I thought I'd mention. Forking the repo and running from there works fine.

**Comment by James-Chahwan** [comment]
What OS, Npm, node version? and copy the output ?

I had these issues running on arch and fixed it by downgrading some packages  ?

**Comment by myamout** [comment]
I'm on Mac OS. NPM version is 5.5.1, Node is 8.9.1, and the output looks like so:
`Error: Cannot find module 'web3-requestManager'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous>`
So it seems some of the dependencies might be missing?

**Comment by myamout** [comment]
Figured out the issue was with Web3 versions. Make sure to install the version of Web3 listed in the JS library's package.json.
