### ISSUE TITLE
Improve documentation redaction & highlighting

### ISSUE THREAD

**Issue by francisbrito** [RequestNetwork/requestNetwork.js#4]
For presentational reasons, it would be nice to have code snippets be highlighted in JavaScript language. This is possible by making some simple changes to the markdown text in the `README.md`.

In the same vein, there are some extra spaces around some method calls that can be removed and `@param` strings that could be highlighted.

I'd like to contribute with this changes if you're OK with it.

**Comment by vrolland** [comment]
Feel free to make PR

**Comment by vrolland** [comment]
PR merged. Thank you !
