### ISSUE TITLE
npm script calls possibly missing `testrpc` command

### ISSUE THREAD

**Issue by francisbrito** [RequestNetwork/requestNetwork.js#8]
It seems the npm script `testrpc` is calling the command `testrpc`, but, since this was not installed as a development nor production dependency, it will not be available in the case the user does not have it installed globally on his/her computer.

Fortunately, this can be easily fixed by adding `testrpc` as either a production or (as it is only used for testing) as a development dependency.

**Comment by etiennetatur** [comment]
Hi Francis, we just commited a fix to the documentation on how to install testrpc to test. Thanks for the comment. 
Check the PR and feel free to reopen the issue/create a PR if you think it could be done differently.
