### ISSUE TITLE
Error: Cannot find module web3-single

### ISSUE THREAD

**Issue by xSam42** [RequestNetwork/requestNetwork.js#9]
I kept getting `Error: Cannot find module './servicesExternal/web3-single'` when trying to compile a project with this library.

I ended up changing the `web3-Single.js` file at `./node_modules/@requestnetwork/request-network.js/dist/src/servicesExternal/web3-Single.js` to `web3-single.js` (lowercase s). My project compiled and ran successfully after that fix - figured someone else might have the same issue.

![fixed](https://user-images.githubusercontent.com/6970865/34749460-917b5216-f56f-11e7-9680-6e2388123329.png)

-Sam

**Comment by vrolland** [comment]
Hello Sam, 
Can you be more specific about: your environment (e.g. node version), your code etc... please?

**Comment by xSam42** [comment]
Sure,

I've got an express project set up at https://github.com/xSam42/req_testing with the change. It just features an express skeleton with some extra packages (https://github.com/xSam42/express_barebones). I figured i needed babel to compile the import statement, I haven't use babel much so it could be user error with that on my end.

Steps to Recreate:
1. Downloaded express skeleton app. 
2. Ran `npm install @requestnetwork/request-network.js --save`
3. Added `import RequestNetwork from '@requestnetwork/request-network.js/dist/src/requestNetwork';` to my app.js file (/req_testing/app.js)
4. Ran `npm install babel-cli`
5. Ran `npm i babel-preset-node6`
6. Ran './node_modules/babel-cli/bin/babel-node.js --presets node6 ./app.js' ( I tried with babel node 6 and node 8 same results)
7. Received Error above.
8. Change web3-Single.js file at ./node_modules/@requestnetwork/request-network.js/dist/src/servicesExternal/web3-Single.js to web3-single.js (lowercase s)
9. Ran step 6 again, was able to compile and run the project 
10. Added `let requestNetwork = new RequestNetwork(); console.log(requestNetwork);` and was able to see the Request object.

**Comment by xSam42** [comment]
Just downloaded the newest changes, the issue/workaround I described above isn't needed anymore. Thanks!
